#!/usr/bin/env sh

echo "Installing XCLIP. It is necessary in order to copy the key to the clipboard.\n"

sudo pacman -S xclip

echo "Your public SSH key is being created and will be copied to your clipboard, if no errors are found.\n"

ssh-keygen -t rsa -C "pedrouminhoribeiro@gmail.com"

SSH_PUB=$HOME/.ssh/id_rsa.pub

if command -v xclip >/dev/null 2>&1; then
    xclip -selection clipboard < "$SSH_PUB"
else
    echo "[ssh]: xclip not found, you need to copy manually the following key"
    cat "$SSH_PUB"
    exit 1
fi

echo "[ssh]: SSH public key copied into the clipboard"
echo "Now you shall paste it into GitHub and/or GitLab"
