#!/bin/bash

SCRIPTS=$HOME/.dotfiles/scripts
BINARIES=/usr/bin

sudo cp $SCRIPTS/utilitary/i3memory 		$BINARIES/i3memory
sudo cp $SCRIPTS/utilitary/i3wifi 		$BINARIES/i3wifi
sudo cp $SCRIPTS/utilitary/i3weather 		$BINARIES/i3weather
sudo cp $SCRIPTS/utilitary/polycpu 		$BINARIES/polycpu
sudo cp $SCRIPTS/utilitary/polypulsevolume 	$BINARIES/polypulsevolume
sudo cp $SCRIPTS/utilitary/polytempamd 			$BINARIES/polytempamd
sudo cp $SCRIPTS/utilitary/updatepackages /usr/bin/updatepackages
sudo cp $SCRIPTS/utilitary/bspfullscreen /usr/bin/bspfullscreen
sudo cp $SCRIPTS/utilitary/bsphide /usr/bin/bsphide
sudo cp $SCRIPTS/utilitary/crystal /usr/bin/crystal
sudo cp $SCRIPTS/utilitary/bspswallow /usr/bin/bspswallow
sudo cp $SCRIPTS/utilitary/bspunhide /usr/bin/bspunhide
sudo cp $SCRIPTS/utilitary/tabc /usr/bin/tabc
sudo cp $SCRIPTS/utilitary/tabdmenu /usr/bin/tabdmenu
sudo cp $SCRIPTS/utilitary/launchpolybar /usr/bin/launchpolybar

